package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.entity.User;
import com.example.demo.entity.UserRequest;
import com.example.demo.entity.UserResponse;
import com.example.demo.service.IUserService;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private IUserService service;

	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user) {

		service.saveUser(user);
		// return new ResponseEntity<String>("User Created ", HttpStatus.OK);
		return ResponseEntity.ok("User Created");
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
		
		AuthenticationManager.authenticate(
			new UsernamePasswordAuthenticationToken(
				userRequest.getUsername(), 
				userRequest.getPassword()
				)
			);
		
		String token = util.generateToken(userRequest.getUsername());

		return ResponseEntity.ok(new UserResponse(token, "Generated By Mr. Raghu"));
	}
	
	

}
